# Generated by Django 4.2.16 on 2026-03-24 03:41

import apps.blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_make_post_thumbnail_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=apps.blog.models.blog_thumbnail_directory),
        ),
    ]
